### ISSUE TITLE
Opengl OSD

### ISSUE THREAD

**Issue by 9000h** [jojo61/vdr-plugin-softhdcuvid#17]
ua0lnj did make some changes, what do you think
https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/3989b14982d023c79c42929c97348e49f25bbb12

**Comment by jojo61** [comment]
See comment from 3PO. This is not the solution fpr your problems with skinnopacity.
Did you try with placebo ? That should work. 
Without placebo there seems a problem with the egl context between opengl OSD and the main process. I will investigate that further.

**Comment by 9000h** [comment]
with 1920x1080 the OSD works without placebo for skinnopacity, when I enable placebo I get short after startup a core (double free).

**Comment by jojo61** [comment]
Could you provide me with a Backtrace of the crash ?  

Without placebo I see every time the OSD is opened a framedrop because the frame can not be convertet to the egl context. If you compile with DEBUG you should see this in the logs.  This may not happen so often with 1920x1080, but it is a bug an I will inbestigate it further on.

**Comment by 9000h** [comment]
the latest git did improve the OSD also with placebo here
